# https://nixpacks.com/docs/configuration/file

# set up some variables to minimize annoyance
[variables]
    NPM_CONFIG_UPDATE_NOTIFIER = 'false'
    NPM_CONFIG_FUND = 'false'
    PYTHONUNBUFFERED = '1'
    # PYTHONPATH = '/app/backend'

[phases.setup]
    nixPkgs = ['nodejs', 'python3', 'postgresql', 'gcc']

[phases.install]
    dependsOn = ['setup']
    cmds = ['npm install']

[phases.build]
    dependsOn = ['install']
    cmds = ['npm run build']

# download caddy from nix
[phases.caddy]
    dependsOn = ['setup']
    nixpkgsArchive = 'ba913eda2df8eb72147259189d55932012df6301'
    nixPkgs = ['caddy']

# format the Caddyfile with fmt
[phases.fmt]
    dependsOn = ['caddy']
    cmds = ['caddy fmt --overwrite Caddyfile']

# start the caddy web server & python backend
[start]
    cmd = 'bash start.sh'
