# https://nixpacks.com/docs/configuration/file

# set up some variables to minimize annoyance
[variables]
    NPM_CONFIG_UPDATE_NOTIFIER = 'false'
    NPM_CONFIG_FUND = 'false'
    PYTHONPATH = 'backend'

[phases.setup]
    nixPkgs = ['nodejs', 'python3']

[phases.install]
    dependsOn = ['setup']
    cmds = ['npm install', 'pip install -r backend/requirements.txt']

[phases.build]
    dependsOn = ['install']
    cmds = ['npm run build']

# download caddy from nix
[phases.caddy]
    dependsOn = ['setup']
    nixpkgsArchive = 'ba913eda2df8eb72147259189d55932012df6301'
    nixPkgs = ['caddy']

# format the Caddyfile with fmt
[phases.fmt]
    dependsOn = ['caddy']
    cmds = ['caddy fmt --overwrite Caddyfile']

# start the caddy web server & python backend
# We set PYTHONPATH to include 'backend' so import resolution works from root
[start]
    cmd = 'uvicorn backend.main:app --host 0.0.0.0 --port 8000 & exec caddy run --config Caddyfile --adapter caddyfile 2>&1'
